services:
  db:
    container_name: hinge_db
    image: 'postgres:16-alpine'
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: hinge_db
      POSTGRES_USER:  postgres
      POSTGRES_PASSWORD:  postgres
    volumes:
      - "postgresdata:/var/lib/postgresql/data"
volumes:
  postgresdata: